#!/bin/sh

# this info is provided throught Android sdk site configuration file:
#
# $HOME/.android/sites-settings.cfg
#
# You can see too:
# see https://developer.android.com/studio/releases/sdk-tools.html
# see https://androidsdkoffline.blogspot.pt/p/android-sdk-tools.html

android_sdk_zip=tools_r25.2.3-linux.zip
android_ndk_zip=android-ndk-r13b-linux-x86_64.zip
apache_ant_tar=apache-ant-1.10.3-bin.tar.gz
wget -c --trust-server-names --max-redirect 5 -P /system/urus/archives/ https://archive.apache.org/dist/ant/binaries/$apache_ant_tar
wget -c --trust-server-names --max-redirect 5 -P /system/urus/archives/ https://dl.google.com/android/repository/$android_ndk_zip
wget -c --trust-server-names --max-redirect 5 -P /system/urus/archives/ https://dl.google.com/android/repository/$android_sdk_zip
mkdir -p /system/urus/opt/apache-ant
unzip -q /system/urus/archives/$android_sdk_zip -d /system/urus/opt/android-sdk
unzip -q /system/urus/archives/$android_ndk_zip -d /system/urus/opt/android-ndk
tar -xvzf /system/urus/archives/$apache_ant_tar -C /system/urus/opt/apache-ant

sudo touch /etc/profile.d/android-sdk.sh
sudo chmod 777 /etc/profile.d/android-sdk.sh
# setup profile environment variables.
cat >/etc/profile.d/android-sdk.sh <<'EOF'
export ANDROID_HOME="/system/urus/opt/android-sdk"
export ANDROID_NDK_HOME="/system/urus/opt/android-ndk"
export APACHE_HOME="/system/urus/opt/apache-ant"
export ANDROID_SDK_HOME="/system/urus/opt/android-sdk"
export ANDROID_NDK_STANDALONE="/system/urus/opt/android-ndkstndaln"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_NDK_HOME/android-ndk-r13b:$APACHE_HOME/apache-ant-1.10.3/bin:$PATH"
export PATH="$JAVA_HOME/bin:$PATH"
export PATH="$ANDROID_NDK_STANDALONE/bin:$PATH"
EOF
. /etc/profile.d/android-sdk.sh

sudo chmod 755 /etc/profile.d/android-sdk.sh

${ANDROID_NDK_HOME}/android-ndk-r13b/build/tools/make-standalone-toolchain.sh --force --verbose --platform=android-21 --install-dir=${ANDROID_NDK_STANDALONE} --arch=arm HOST_ARCH=x86_64

#/usr/bin/install_jdk.sh

# install packages.
# NB list available packages with android list sdk --all --extended
android_packages="platform-tools,build-tools-23.0.3,android-21"

if [ "x$CI_BUILD" != "x" ] ; then
printf "y\n" | android update sdk --all --filter ${android_packages} --no-ui
else
android update sdk --all --filter ${android_packages} --no-ui
fi

exit 0

