#! /bin/sh

# this info is provided throught Android sdk site configuration file:
#
# $HOME/.android/sites-settings.cfg
#
# You can see too:
# see https://developer.android.com/studio/releases/sdk-tools.html
# see https://androidsdkoffline.blogspot.pt/p/android-sdk-tools.html

android_sdk_zip=tools_r25.2.3-windows.zip
android_ndk_zip=android-ndk-r13b-windows-x86.zip
apache_ant_tar=apache-ant-1.10.3-bin.tar.gz
wget -c --trust-server-names --max-redirect 5 -P /archives/ http://www-us.apache.org/dist//ant/binaries/$apache_ant_tar
wget -c --trust-server-names --max-redirect 5 -P /archives/ https://dl.google.com/android/repository/$android_ndk_zip
wget -c --trust-server-names --max-redirect 5 -P /archives/ https://dl.google.com/android/repository/$android_sdk_zip
unzip -q /archives/$android_sdk_zip -d /opt/android-sdk
unzip -q /archives/$android_ndk_zip -d /opt/android-ndk
mkdir -p /opt/apache-ant
tar -xvzf /archives/$apache_ant_tar -C /opt/apache-ant

# setup profile environment variables.
cat >/etc/profile.d/android-sdk.sh <<'EOF'
export ANDROID_HOME='/opt/android-sdk'
export ANDROID_NDK_HOME='/opt/android-ndk'
export APACHE_HOME='/opt/apache-ant'
export ANDROID_SDK_HOME='/opt/android-sdk'
export ANDROID_NDK_STANDALONE='/opt/android-ndkstndaln'
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_NDK_HOME/android-ndk-r13b:$APACHE_HOME/apache-ant-1.10.3/bin:$PATH"
export PATH="$JAVA_HOME/bin:$PATH"
export PATH="$ANDROID_NDK_STANDALONE/bin:$PATH"
EOF
. /etc/profile.d/android-sdk.sh

cd /archives/packages/android-ndk-r13b
./patchpkg.sh
$ANDROID_NDK_HOME/android-ndk-r13b/build/tools/make-standalone-toolchain.sh --force --verbose --platform=android-21 --install-dir=$ANDROID_NDK_STANDALONE --arch=arm
cd $HOME

#/usr/bin/install_jdk.sh

# install packages.
# NB list available packages with android list sdk --all --extended
android_packages=(
    #tools
    platform-tools
    build-tools-23.0.3
    #android-24
    #sys-img-armeabi-v7a-android-24
    #sys-img-x86-android-24 # NB thid needs kvm support. they won't work inside a VirtualBox VM.
    #sys-img-x86_64-android-24
    android-21
    #android-25 emulators does not seem to work at all...
    #sys-img-x86-google_apis-25
    #sys-img-x86_64-google_apis-25
    #extra-android-m2repository
    #extra-google-m2repository
)

if [ "x$CI_BUILD" != "x" ] ; then
expect <<EOF
set timeout -1;
spawn android.bat update sdk --all --filter $(IFS=,;echo "${android_packages[*]}") --no-ui;
expect {
    "Do you accept the license" { exp_send "y\r" ; exp_continue }
    eof
}
EOF
else
    android.bat update sdk --all --filter $(IFS=,;echo "${android_packages[*]}") --no-ui;
fi
